=== eID-Testbeds/server/CommonTestbedUtilities/BouncyCertGenerator/src/main/resources/cv_schema.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns="http://www.secunet.com" targetNamespace="http://www.secunet.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<!-- types for the XML doc -->
	<xs:simpleType name="algorithmType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TA_RSA_v1_5_SHA_1" />
			<xs:enumeration value="TA_RSA_v1_5_SHA_256" />
			<xs:enumeration value="TA_RSA_PSS_SHA_1" />
			<xs:enumeration value="TA_RSA_PSS_SHA_256" />
			<xs:enumeration value="TA_ECDSA_SHA_1" />
			<xs:enumeration value="TA_ECDSA_SHA_224" />
			<xs:enumeration value="TA_ECDSA_SHA_256" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="publicKeyType" >
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="domainParam" type="xs:boolean"/> <!-- default: false -->
			</xs:extension>
		</xs:simpleContent>	
	</xs:complexType>
	
	<xs:complexType name="signKeyType">
		<xs:simpleContent>
			<xs:extension base="xs:string" />
		</xs:simpleContent>	
	</xs:complexType>

	<xs:complexType name="certHolderAuthType">
		<xs:sequence>
			<xs:element name="role" type="roleType" />
			<xs:element name="writeDG17" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="writeDG18" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="writeDG19" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="writeDG20" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="writeDG21" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG1" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG2" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG3" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG4" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG5" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG6" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG7" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG8" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG9" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG10" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG11" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG12" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG13" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG14" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG15" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG16" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG17" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG18" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG19" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG20" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readDG21" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="installQualifiedCertificate" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="installCertificate" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="pinManagement" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="canAllowed" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="privilegedTerminal" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="restrictedIdentification" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="communityIDVerification" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="ageVerification" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readEPassDG3" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="readEPassDG4" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="generateQualifiedElectronicSignature" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="generateElectronicSignature" type="xs:boolean" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="type" type="terminalType" use="required" />
		<xs:attribute name="forceOID" type="xs:hexBinary" use="optional" />
	</xs:complexType>

	<xs:simpleType name="roleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CVCA" />
			<xs:enumeration value="DV_DOMESTIC" />
			<xs:enumeration value="DV_FOREIGN" />
			<xs:enumeration value="TERMINAL" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="terminalType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AT" />
			<xs:enumeration value="IS" />
			<xs:enumeration value="ST" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="profileIdType">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]{1}" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="keyType">
		<xs:sequence>
			<xs:element name="filePrivateKey" type="xs:string" />
			<xs:element name="filePublicKey" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:sequence>
				<xs:element name="algorithm" type="algorithmType" />
				<xs:choice>
					<xs:element name ="ecdsa" type="ecdsaType" />
					<xs:element name="rsa">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="publicExpo" type="xs:integer" minOccurs="0"/>
								<xs:element name="length" type="keyLengthType" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="create" type="xs:boolean" /> <!-- default: false -->
	</xs:complexType>
	
	<xs:complexType name="descriptionType">
		<xs:sequence>
			<xs:element name="issuerName" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="issuerURL" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="subjectName" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="subjectURL" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:choice>
				<xs:element name="fileTermsOfUsage" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="termsOfUsage" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:choice>
			<xs:element name="redirectURL" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="commCerts" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="fileCommCert" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
						<xs:element name="hashCommCert" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="fileDescription" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="import" type="xs:boolean" /> <!-- default: false -->
	</xs:complexType>
	
	<xs:complexType name="terminalSectorType">
		<xs:sequence>
			<xs:element name="fileSectorPublicKey" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="ecdsaType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ASN1::secp112r1" />
			<xs:enumeration value="ASN1::secp112r2" />
			<xs:enumeration value="ASN1::secp128r1" />
			<xs:enumeration value="ASN1::secp128r2" />
			<xs:enumeration value="ASN1::secp160r1" />
			<xs:enumeration value="ASN1::secp160k1" />
			<xs:enumeration value="ASN1::secp160r2" />
			<xs:enumeration value="ASN1::secp192k1" />
			<xs:enumeration value="ASN1::secp192r1" />
			<xs:enumeration value="ASN1::secp224k1" />
			<xs:enumeration value="ASN1::secp224r1" />
			<xs:enumeration value="ASN1::secp256k1" />
			<xs:enumeration value="ASN1::secp256r1" />
			<xs:enumeration value="ASN1::secp384r1" />
			<xs:enumeration value="ASN1::secp521r1" />
			<xs:enumeration value="BRAINPOOL::p160r1" />
			<xs:enumeration value="BRAINPOOL::p160t1" />
			<xs:enumeration value="BRAINPOOL::p192r1" />
            <xs:enumeration value="BRAINPOOL::p192t1" />
			<xs:enumeration value="BRAINPOOL::p224r1" />
			<xs:enumeration value="BRAINPOOL::p224t1" />
			<xs:enumeration value="BRAINPOOL::p256r1" />
			<xs:enumeration value="BRAINPOOL::p256t1" />
			<xs:enumeration value="BRAINPOOL::p320r1" />
			<xs:enumeration value="BRAINPOOL::p320t1" />
			<xs:enumeration value="BRAINPOOL::p384r1" />
			<xs:enumeration value="BRAINPOOL::p384t1" />
			<xs:enumeration value="BRAINPOOL::p512r1" />
			<xs:enumeration value="BRAINPOOL::p512t1" />
		</xs:restriction>	
	</xs:simpleType>
	
	<xs:simpleType name="keyLengthType">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="512" />
			<xs:enumeration value="1024" />
			<xs:enumeration value="1280" />
			<xs:enumeration value="1536" />
			<xs:enumeration value="2048" />
			<xs:enumeration value="3072" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- structure of the XML doc -->
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="keys" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="key" type="keyType" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="cert" type="certType" maxOccurs="unbounded" />			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="certType">
		<xs:sequence>
			<xs:element name="profileId" type="profileIdType" />
			<xs:element name="certAuthRef" type="xs:string" />
			<xs:element name="publicKey" type="publicKeyType" maxOccurs="1" />
			<xs:element name="certHolderRef" type="xs:string" />
			<xs:element name="certHolderAuth" type="certHolderAuthType" minOccurs="0" maxOccurs="1" />
			<xs:choice>
				<xs:element name="effDate" type="xs:date" />
				<xs:element name="effDateOffset" type="xs:integer" />
			</xs:choice>
			<xs:choice>
				<xs:element name="expDate" type="xs:date" />
				<xs:element name="expDateOffset" type="xs:integer" />
			</xs:choice>
			<xs:element name="extensions" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="descriptionType" minOccurs="0" maxOccurs="1" />
						<xs:element name="terminalSector" type="terminalSectorType" minOccurs="0" maxOccurs="2" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="signKey" type="signKeyType" maxOccurs="1" />
			<xs:element minOccurs="0" maxOccurs="1" name="outputFile">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="createAdditionalHexFile" type="xs:boolean" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== eID-Testbeds/server/eidsrv-testbed-runner/CVCertificates.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="http://www.secunet.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.secunet.com cv_schema.xsd">

	<keys>
		<key name="CVCA1_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_CVCA_1.pkcs8</filePrivateKey>
			<filePublicKey>./keys/CERT_ECARD_CV_CVCA_1.x509</filePublicKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="DV1A_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_DV_1_A.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="TERM1A_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_TERM_1_A.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="TERM1B_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_TERM_1_B.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="TERM1C_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_TERM_1_C.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="TERM1D_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_TERM_1_D.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="SECTOR1_KEY" create="true">
			<filePrivateKey>./keys/TERM_SECTOR1.pkcs8</filePrivateKey>
			<filePublicKey>./keys/TERM_SECTOR1.x509</filePublicKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="SECTOR2_KEY" create="true">
			<filePrivateKey>./keys/TERM_SECTOR2.pkcs8</filePrivateKey>
			<filePublicKey>./keys/TERM_SECTOR2.x509</filePublicKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="CVCA2A_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_CVCA_2_A.pkcs8</filePrivateKey>
			<filePublicKey>./keys/CERT_ECARD_CV_CVCA_2_A.x509</filePublicKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="CVCA2B_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_CVCA_2_B.pkcs8</filePrivateKey>
			<filePublicKey>./keys/CERT_ECARD_CV_CVCA_2_B.x509</filePublicKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="CVCA2C_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_CVCA_2_C.pkcs8</filePrivateKey>
			<filePublicKey>./keys/CERT_ECARD_CV_CVCA_2_C.x509</filePublicKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="DV2A_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_DV_2_A.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
		<key name="TERM2A_KEY" create="true">
			<filePrivateKey>./keys/CERT_ECARD_CV_TERM_2_A.pkcs8</filePrivateKey>
			<algorithm>TA_ECDSA_SHA_256</algorithm>
			<ecdsa>BRAINPOOL::p256r1</ecdsa>			
		</key>
	</keys>

	<!-- ROOT CVCA1 Certificate -->
	<cert>
		<profileId>0</profileId>
		<certAuthRef>DEESTCVCA100001</certAuthRef>
		<publicKey domainParam="true">CVCA1_KEY</publicKey>
		<certHolderRef>DEESTCVCA100001</certHolderRef>
		<certHolderAuth type="AT">
			<role>CVCA</role>
			<writeDG17>true</writeDG17>
			<writeDG18>true</writeDG18>
			<writeDG19>true</writeDG19>
			<writeDG20>true</writeDG20>
			<writeDG21>true</writeDG21>
			<readDG1>true</readDG1>
			<readDG2>true</readDG2>
			<readDG3>true</readDG3>
			<readDG4>true</readDG4>
			<readDG5>true</readDG5>
			<readDG6>true</readDG6>
			<readDG7>true</readDG7>
			<readDG8>true</readDG8>
			<readDG9>true</readDG9>
			<readDG10>true</readDG10>
			<readDG11>true</readDG11>
			<readDG12>true</readDG12>
			<readDG13>true</readDG13>
			<readDG14>true</readDG14>
			<readDG15>true</readDG15>
			<readDG16>true</readDG16>
			<readDG17>true</readDG17>
			<readDG18>true</readDG18>
			<readDG19>true</readDG19>
			<readDG20>true</readDG20>
			<readDG21>true</readDG21>
			<installQualifiedCertificate>true</installQualifiedCertificate>
			<installCertificate>true</installCertificate>
			<pinManagement>true</pinManagement>
			<canAllowed>true</canAllowed>
			<privilegedTerminal>true</privilegedTerminal>
			<restrictedIdentification>true</restrictedIdentification>
			<communityIDVerification>true</communityIDVerification>
			<ageVerification>true</ageVerification>
		</certHolderAuth>
		<effDate>2016-04-01</effDate>
		<expDateOffset>6000</expDateOffset>
		<signKey>CVCA1_KEY</signKey>
		<outputFile>./certs/CERT_ECARD_CV_CVCA_1.cvcert</outputFile>
	</cert>

	<!-- DV1A Certificate -->
	<cert>
		<profileId>0</profileId>
		<certAuthRef>DEESTCVCA100001</certAuthRef>
		<publicKey>DV1A_KEY</publicKey>
		<certHolderRef>DEESTDV1A00001</certHolderRef>
		<certHolderAuth type="AT">
			<role>DV_DOMESTIC</role>
			<writeDG17>true</writeDG17>
			<writeDG18>true</writeDG18>
			<writeDG19>true</writeDG19>
			<writeDG20>true</writeDG20>
			<writeDG21>true</writeDG21>
			<readDG1>true</readDG1>
			<readDG2>true</readDG2>
			<readDG3>true</readDG3>
			<readDG4>true</readDG4>
			<readDG5>true</readDG5>
			<readDG6>true</readDG6>
			<readDG7>true</readDG7>
			<readDG8>true</readDG8>
			<readDG9>true</readDG9>
			<readDG10>true</readDG10>
			<readDG11>true</readDG11>
			<readDG12>true</readDG12>
			<readDG13>true</readDG13>
			<readDG14>true</readDG14>
			<readDG15>true</readDG15>
			<readDG16>true</readDG16>
			<readDG17>true</readDG17>
			<readDG18>true</readDG18>
			<readDG19>true</readDG19>
			<readDG20>true</readDG20>
			<readDG21>true</readDG21>
			<installQualifiedCertificate>true</installQualifiedCertificate>
			<installCertificate>true</installCertificate>
			<pinManagement>true</pinManagement>
			<canAllowed>true</canAllowed>
			<privilegedTerminal>true</privilegedTerminal>
			<restrictedIdentification>true</restrictedIdentification>
			<communityIDVerification>true</communityIDVerification>
			<ageVerification>true</ageVerification>
		</certHolderAuth>
		<effDateOffset>0</effDateOffset>
		<expDateOffset>5000</expDateOffset>
		<signKey>CVCA1_KEY</signKey>
		<outputFile>./certs/CERT_ECARD_CV_DV_1_A.cvcert</outputFile>
	</cert>

	<!-- AT Certificate -->
	<cert>
		<profileId>0</profileId>
		<certAuthRef>DEESTDV1A00001</certAuthRef>
		<publicKey>TERM1A_KEY</publicKey>
		<certHolderRef>DEESTTERM1A00001</certHolderRef>
		<certHolderAuth type="AT">
			<role>TERMINAL</role>
			<writeDG17>true</writeDG17>
			<writeDG18>true</writeDG18>
			<writeDG19>true</writeDG19>
			<writeDG20>true</writeDG20>
			<readDG1>true</readDG1>
			<readDG2>true</readDG2>
			<readDG3>true</readDG3>
			<readDG4>true</readDG4>
			<readDG5>true</readDG5>
			<readDG6>true</readDG6>
			<readDG7>true</readDG7>
			<readDG8>true</readDG8>
			<readDG9>true</readDG9>
			<readDG10>true</readDG10>
			<readDG13>true</readDG13>
			<readDG14>true</readDG14>
			<readDG15>true</readDG15>
			<readDG16>true</readDG16>
			<readDG17>true</readDG17>
			<readDG18>true</readDG18>
			<readDG19>true</readDG19>
			<readDG20>true</readDG20>
			<installQualifiedCertificate>true</installQualifiedCertificate>
			<installCertificate>true</installCertificate>
			<pinManagement>true</pinManagement>
			<canAllowed>true</canAllowed>
			<privilegedTerminal>true</privilegedTerminal>
			<restrictedIdentification>true</restrictedIdentification>
			<communityIDVerification>true</communityIDVerification>
			<ageVerification>true</ageVerification>
		</certHolderAuth>
		<effDateOffset>0</effDateOffset>
		<expDateOffset>4000</expDateOffset>
		<extensions>
			<description>
				<issuerName>secunet</issuerName>
				<subjectName>eID-Server Testbed</subjectName>
				<subjectURL>https://some.test.url.de</subjectURL>
				<!-- <fileTermsOfUsage>./desc/ATSN01.txt</fileTermsOfUsage> -->
				<termsOfUsage>CV Terms of Usage</termsOfUsage>
				<commCerts>
					<!-- <fileCommCert>./keys/ServerCertificate.der</fileCommCert> -->
					<hashCommCert>71B89F97689425CCAD573F4754D74BAAFDBB95980D9135605EED4BF29781674C</hashCommCert>
					<hashCommCert>5C6FCAC6857D69B469B8E8E523B656338BDDA1AC43DEA739E0510C862901D06D</hashCommCert>
				</commCerts>
				<fileDescription>./desc/CERT_ECARD_CV_TERM_1_A.bin</fileDescription>
			</description>
			<!-- <description import="true">
				<fileDescription>./desc/TerminalCertificateDesc.bin</fileDescription>
			</description> -->
			<terminalSector>
				<fileSectorPublicKey>./keys/TERM_SECTOR1.x509.cv</fileSectorPublicKey>
			</terminalSector>
		</extensions>
		<signKey>DV1A_KEY</signKey>
		<outputFile>./certs/CERT_ECARD_CV_TERM_1_A.cvcert</outputFile>
	</cert>

	<!-- AT Certificate -->
	<cert>
		<profileId>0</profileId>
		<certAuthRef>DEESTDV1A00001</certAuthRef>
		<publicKey>TERM1B_KEY</publicKey>
		<certHolderRef>DEESTTERM1B00001</certHolderRef>
		<certHolderAuth type="AT">
			<role>TERMINAL</role>
			<writeDG17>false</writeDG17>
			<writeDG18>false</writeDG18>
			<writeDG19>false</writeDG19>
			<writeDG20>false</writeDG20>
			<readDG1>false</readDG1>
			<readDG2>false</readDG2>
			<readDG3>false</readDG3>
			<readDG4>false</readDG4>
			<readDG5>true</readDG5>
			<readDG6>false</readDG6>
			<readDG7>false</readDG7>
			<readDG8>false</readDG8>
			<readDG9>false</readDG9>
			<readDG10>false</readDG10>
			<readDG13>false</readDG13>
			<readDG14>false</readDG14>
			<readDG15>false</readDG15>
			<readDG16>false</readDG16>
			<readDG17>false</readDG17>
			<readDG18>false</readDG18>
			<readDG19>false</readDG19>
			<readDG20>false</readDG20>
