=== eID-Testbeds/server/eidsrv-testbed-testgenerator/src/main/resources/xmlScheme/sn_TestcaseDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.secunet.com" targetNamespace="http://www.secunet.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="testcaseDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" minOccurs="1" maxOccurs="1"
					type="xs:string" />
				<xs:element name="description" minOccurs="1" maxOccurs="1"
					type="xs:string" />
				<xs:element name="modulePath" minOccurs="1" maxOccurs="1"
					type="modulePath" />
				<xs:element name="manualExplanation" minOccurs="0"
					maxOccurs="1" type="xs:string" />
				<xs:element name="profiles" minOccurs="1" type="profiles" />
				<xs:element name="eservice" minOccurs="1" maxOccurs="1"
					type="eService" default="A" />
				<xs:element name="clientExplanation" minOccurs="0"
					maxOccurs="1" type="xs:string">
					<xs:annotation>
            			<xs:documentation>This text will be displayed for test subjects which do not have the capability to handle multiple clients.</xs:documentation>
          			</xs:annotation>
					</xs:element>
				<xs:element name="eidcard" minOccurs="0" maxOccurs="1"
					type="eidCard" />
				<xs:element name="certificateBaseNames" type="certNames"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="steps" type="stepsType" />
				<xs:element name="variables" type="variables" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="eService">
		<xs:restriction base="xs:string">
			<!-- using cert set 1 -->
			<xs:enumeration value="A" />
			<xs:enumeration value="B" />
			<xs:enumeration value="C" />
			<xs:enumeration value="D" />
			<xs:enumeration value="EDSA" />
			<xs:enumeration value="ERSA" />
			<xs:enumeration value="EECDSA" />
			<xs:enumeration value="F" />
			<!-- using cert set 2 -->
			<xs:enumeration value="A2" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="eidCard">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EIDCARD_1" />
			<xs:enumeration value="EIDCARD_2" />
			<xs:enumeration value="EIDCARD_3" />
			<xs:enumeration value="EIDCARD_4" />
			<xs:enumeration value="EIDCARD_5" />
			<xs:enumeration value="EIDCARD_6" />
			<xs:enumeration value="EIDCARD_7" />
			<xs:enumeration value="EIDCARD_8" />
			<xs:enumeration value="EIDCARD_9" />
			<xs:enumeration value="EIDCARD_10" />
			<xs:enumeration value="EIDCARD_11" />
			<xs:enumeration value="EIDCARD_12_1" />
			<xs:enumeration value="EIDCARD_12_2" />
			<xs:enumeration value="EIDCARD_12_3" />
			<xs:enumeration value="EIDCARD_13" />
			<xs:enumeration value="EIDCARD_14" />
			<xs:enumeration value="EIDCARD_15" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="modulePath">
		<xs:sequence>
			<xs:element name="node" minOccurs="1" maxOccurs="unbounded"
				type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="stepsType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="step" minOccurs="0" maxOccurs="unbounded"
				type="testStepType" />
			<xs:element name="reference" type="referenceType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>


	<xs:complexType name="referenceType">
		<xs:simpleContent>
			<xs:extension base="testcaseNameType">
				<xs:attribute name="targetInterface" type="targetInterfaceType"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="testcaseNameType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="targetInterfaceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="eID-Interface" />
			<xs:enumeration value="eCard-API" />
			<xs:enumeration value="SAML" />
			<xs:enumeration value="Attached" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="testStepType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IN_ATTACHED_WEBPAGE" />
			<xs:enumeration value="IN_BAD_REQUEST" />
			<xs:enumeration value="IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE" />
			<xs:enumeration value="IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE_REQCHAT_SET1" />
			<xs:enumeration value="IN_DID_AUTHENTICATE_EAC_2_INPUTTYPE" />
			<xs:enumeration value="IN_DID_AUTHENTICATE_EACADDITIONALINPUTTYPE" />
			<xs:enumeration value="IN_DIDLIST" />
			<xs:enumeration value="IN_DISCONNECT" />
			<xs:enumeration value="IN_EIDAS_BAD_REQUEST" />
			<xs:enumeration value="IN_EIDAS_RESPONSE" />
			<xs:enumeration value="IN_EIDAS_RESPONSE_POST" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_AGEPLACE" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_EIDCARD_2" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_EIDCARD_3" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_ERROR" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_ERROR_2" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_NORESULTYET" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_RESTRICTEDID" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_SET1" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_PLACE" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_AGE" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_PLACE_OPTIONAL" />
			<xs:enumeration value="IN_GETRESULT_RESPONSE_AGE_OPTIONAL" />
			<xs:enumeration value="OUT_GETRESULT_REQUEST_TWO_REQUESTCOUNTERS" />
			<xs:enumeration value="IN_GETSERVERINFO_RESPONSE" />
			<xs:enumeration value="IN_INITIALIZE_FRAMEWORK" />
			<xs:enumeration value="IN_MISC" />
			<xs:enumeration value="IN_SAML_ASSERTION" />
			<xs:enumeration value="IN_START_PAOS_RESPONSE" />
			<xs:enumeration value="IN_START_PAOS_RESPONSE_INTERNAL_ERROR" />
			<xs:enumeration value="IN_START_PAOS_RESPONSE_CUSTOM_ERROR" />
			<xs:enumeration value="IN_TC_TOKEN" />			<!-- The TC Token received from the SAML processor -->
			<xs:enumeration value="IN_TC_TOKEN_ATTACHED" />			<!-- The TC Token of the attached eService -->
			<xs:enumeration value="IN_TC_TOKEN_SAML_ATTACHED" />
			<xs:enumeration value="IN_TLS" />
			<xs:enumeration value="IN_TRANSMIT" />
			<xs:enumeration value="IN_USEID_RESPONSE" />
			<xs:enumeration value="IN_USEID_RESPONSE_NO_PSK" />
			<xs:enumeration value="IN_USEID_RESPONSE_ERROR" />
			<xs:enumeration value="IN_USEID_RESPONSE_PSK" />
			<xs:enumeration value="IN_USEID_RESPONSE_PSK_ERROR" />
			<xs:enumeration value="IN_USEID_RESPONSE_UNIQUE" />
			<xs:enumeration value="OUT_CALL_SAML_INCL_AUTHNREQUEST" />		<!-- The request for the TC Token (only SAML) -->
			<xs:enumeration
				value="OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGALG_NO_SIGNATURE" />
			<xs:enumeration value="OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGNATURE" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CHAT" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHAT" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_IDPICC" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CUSTOM_CHAT" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHALLENGE" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_INTERNALERROR" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_CUSTOM_AUTHTOKEN" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_EFCARDSECURITY" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_AUTHENTICATIONTOKEN" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_EFCARDSECURITY" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_AUTHENTICATIONTOKEN" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_NONCE" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_NONCE" />
			<xs:enumeration
				value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_INTERNALERROR" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B" />
			<xs:enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B_MANDATORY" />
			<xs:enumeration value="OUT_DIDLIST" />
			<xs:enumeration value="OUT_DISCONNECT" />
			<xs:enumeration value="OUT_EIDAS_REQUEST" />
			<xs:enumeration value="OUT_EIDAS_REQUEST_POST" />
			<xs:enumeration value="OUT_EIDAS_REQUEST_NO_SIGALG_NO_SIGNATURE" />
			<xs:enumeration value="OUT_EIDAS_REQUEST_NO_SIGNATURE" />
			<xs:enumeration value="OUT_EIDAS_RESPONSE" />
			<xs:enumeration value="OUT_GET_TCTOKEN" />		<!-- The request for the TC Token (only attached SOAP) -->
			<xs:enumeration value="OUT_GET_ATTACHED_WEBPAGE" />		<!-- The request for the webpage containing the link to the TC Token (only attached SOAP) -->
			<xs:enumeration value="OUT_GETRESULT_REQUEST" />
			<xs:enumeration value="OUT_GETRESULT_REQUEST_NO_REQUESTCOUNTER" />
			<xs:enumeration value="OUT_GETRESULT_REQUEST_NO_SID" />
			<xs:enumeration value="OUT_GETRESULT_REQUEST_REQUESTCOUNTER" />
			<xs:enumeration value="OUT_GETRESULT_REQUEST_SID" />
			<xs:enumeration value="OUT_GETSERVERINFO_REQUEST" />
			<xs:enumeration value="OUT_INITIALIZE_FRAMEWORK_RESPONSE" />
			<xs:enumeration value="OUT_INITIALIZE_FRAMEWORK_RESPONSE_EMPTY_RESULT" />
			<xs:enumeration value="OUT_MISC" />
			<xs:enumeration value="OUT_SAML_ASSERTION" />
			<xs:enumeration value="OUT_START_PAOS" />
			<xs:enumeration value="OUT_START_PAOS_DIDPROTOCOLS" />
			<xs:enumeration value="OUT_TLS_ATTACHED" />
			<xs:enumeration value="OUT_TLS_ECARDAPI" />
			<xs:enumeration value="OUT_TLS_EID" />
			<xs:enumeration value="OUT_TLS_SAML" />
			<xs:enumeration value="OUT_TRANSMIT" />
			<xs:enumeration value="OUT_TRANSMIT_INVALID_MAC" />
			<xs:enumeration value="OUT_TRANSMIT_NO_APDUS" />
			<xs:enumeration value="OUT_TRANSMIT_NO_MAC" />
			<xs:enumeration value="OUT_USEID_REQUEST" />
			<xs:enumeration value="OUT_USEID_REQUEST_ALL" />
			<xs:enumeration value="OUT_USEID_REQUEST_NO_AGEVERIFICATIONREQUEST" />
			<xs:enumeration value="OUT_USEID_REQUEST_NO_PLACEVERIFICATIONREQUEST" />
			<xs:enumeration value="OUT_USEID_REQUEST_NO_USEOPERATIONS" />
			<xs:enumeration value="OUT_USEID_REQUEST_PSK" />
			<xs:enumeration value="OUT_USEID_REQUEST_SET1" />
			<xs:enumeration value="OUT_USEID_REQUEST_PLACE" />
			<xs:enumeration value="OUT_USEID_REQUEST_AGE" />
			<xs:enumeration value="OUT_USEID_REQUEST_NO_XMLSIGNATURE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="profiles">
		<xs:sequence>
			<xs:element name="profile" type="profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="profile">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PAOS" />
			<xs:enumeration value="EAC" />
			<xs:enumeration value="EID_ACCESS" />
			<xs:enumeration value="REVOKED_CARD" />
			<xs:enumeration value="EXPIRED_CARD" />
			<xs:enumeration value="NONAUTH_CARD" />
			<xs:enumeration value="RI_MIGRATION" />
			<xs:enumeration value="CRYPTO" />
			<xs:enumeration value="DG_VARIATIONS" />
			<xs:enumeration value="SOAP" />
			<xs:enumeration value="SOAP_TLS" />
			<xs:enumeration value="SAML" />
			<xs:enumeration value="SAML_ATTACHED" />
			<xs:enumeration value="ESER_ATTACHED" />
			<xs:enumeration value="TLS_PSK" />
			<xs:enumeration value="TLS_ETM" />
			<xs:enumeration value="ALL_LINK" />
			<xs:enumeration value="CONF_MAX_SE" />
			<xs:enumeration value="CONF_TM_OUT" />
			<xs:enumeration value="EIDAS_MW" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="certNames">
		<xs:sequence>
			<xs:element name="certificate" type="certName" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="certName">
		<xs:restriction base="xs:string">
			<!-- CERT_SET_1 -->
			<xs:enumeration value="CERT_ECARD_TLS_EIDSERVER_1" />
			<xs:enumeration value="CERT_ECARD_TLS_SAMLPROCESSOR_1_" />
			<xs:enumeration value="CERT_EID_TLS_EIDSERVER_1" />
			
			<!-- CERT_SET_2 -->
			<xs:enumeration value="CERT_EID_TLS_ESERVICE_2_A" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="variables">
		<xs:choice>
			<xs:element name="variable" minOccurs="1" maxOccurs="unbounded"
				type="variable" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="variable">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required">
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- step definitions -->

	<xs:element name="Step">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TargetInterface" type="targetInterfaceType" />
				<xs:element name="Optional" minOccurs="0" maxOccurs="1"
					type="xs:boolean" />
				<xs:element name="Schema" minOccurs="0" maxOccurs="1"
					type="xs:string" />
				<xs:element name="TlsStepToken" minOccurs="0" maxOccurs="unbounded"
					type="stepToken" />
				<xs:element name="HttpStepToken" minOccurs="0" maxOccurs="unbounded"
					type="stepToken" />
				<xs:element name="ProtocolStepToken" minOccurs="0"
					maxOccurs="unbounded" type="stepToken" />
				<xs:element name="ToSave" minOccurs="0" maxOccurs="unbounded"
					type="optAttrString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="stepToken">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="parentName" type="xs:string" minOccurs="0" />
			<xs:element name="value" type="xs:string" minOccurs="0" />
			<xs:element name="attributes" type="attributes" minOccurs="0" />
			<xs:element name="maxNumberOfOccurences" type="xs:positiveInteger"
				minOccurs="0" /> <!-- Maximum number of times this element is allowed to occur. If this is 
				not provided, the value is set to 1 -->
			<xs:element name="isMandatory" type="xs:boolean"
				minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="negate" type="xs:boolean" default="false"/>
	</xs:complexType>

	<xs:complexType name="optAttrString">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="parentName" type="xs:string" />
				<xs:attribute name="placeholder" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="attributes">
		<xs:sequence>
			<xs:element name="attribute" type="attribute" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="attribute">
		<xs:sequence>
			<xs:element name="name" minOccurs="1" type="xs:string" />
			<xs:element name="value" minOccurs="1" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== eID-Testbeds/server/eidsrv-testbed-testgenerator/src/main/resources/steps/IN_GETRESULT_RESPONSE.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Step xmlns:p="http://www.secunet.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.secunet.com ../xmlScheme/sn_TestcaseDefinition.xsd" >
	<p:TargetInterface>eID-Interface</p:TargetInterface>
	<!-- Schema name -->
	<!--<p:Schema>PROVIDE_XSD</p:Schema> -->
	<!-- HTTP Tokens -->
	<p:HttpStepToken>
		<p:name>HTTP_STATUS_CODE</p:name>
		<p:value>HTTP/1.1 200 OK</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:HttpStepToken>
	<p:HttpStepToken>
		<p:name>Content-Type</p:name>
		<p:value>text/xml;charset=utf-8</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:HttpStepToken>
	<!-- Protocol tokens -->
	<p:ProtocolStepToken>
		<p:name>ResultMajor</p:name>
		<p:value>http://www.bsi.bund.de/ecard/api/1.1/resultmajor#ok</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>getResultResponse</p:name>
		<p:value></p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>PersonalData</p:name>
		<p:value></p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>OperationsAllowedByUser</p:name>
		<p:value></p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	
	<!-- The message must also contain the element "OperationsAllowedByUser" which marks [ATTRIBUTE_A] as ALLOWED and the remaining attributes as PROHIBITED. -->
	<p:ProtocolStepToken>
		<p:name>DocumentType</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_DOCUMENTTYPE]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>IssuingState</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_ISSUINGSTATE]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>DateOfExpiry</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_DATEOFEXPIRY]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>GivenNames</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_GIVENNAMES]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>FamilyNames</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_FAMILYNAMES]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ArtisticName</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_ARTISTICNAME]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>AcademicTitle</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_ACADEMICTITLE]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>DateOfBirth</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_DATEOFBIRTH]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>PlaceOfBirth</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_PLACEOFBIRTH]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>Nationality</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_NATIONALITY]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>BirthName</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_BIRTHNAME]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>PlaceOfResidence</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_PLACEOFRESIDENCE]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ResidencePermitI</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_RESIDENCEPERMITI]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>RestrictedID</p:name>
		<p:parentName>OperationsAllowedByUser</p:parentName>
		<p:value>[OABU_RESTRICTEDID]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>AgeVerification</p:name>
		<p:value>PROHIBITED</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>PlaceVerification</p:name>
		<p:value>PROHIBITED</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	
	<!-- the values for personal data -->
	<p:ProtocolStepToken>
		<p:name>DocumentType</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_DOCUMENTTYPE]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>IssuingState</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_ISSUINGSTATE]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>DateOfExpiry</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_DATEOFEXPIRY]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>GivenNames</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_GIVENNAMES]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>FamilyNames</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_FAMILYNAMES]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ArtisticName</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_ARTISTICNAME]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>AcademicTitle</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_ACADEMICTITLE]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>DateString</p:name>
		<p:parentName>DateOfBirth</p:parentName>
		<p:value>[PERSONAL_DATEOFBIRTH]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>FreetextPlace</p:name>
		<p:parentName>PlaceOfBirth</p:parentName>
		<p:value>[PERSONAL_PLACEOFBIRTH]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>Nationality</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_NATIONALITY]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>BirthName</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_BIRTHNAME]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>PlaceOfResidence</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_PLACEOFRESIDENCE]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ResidencePermitI</p:name>
		<p:parentName>PersonalData</p:parentName>
		<p:value>[PERSONAL_RESIDENCEPERMITI]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ID</p:name>
		<p:parentName>RestrictedID</p:parentName>
		<p:value>[PERSONAL_RESTRICTEDID]</p:value>
		<p:isMandatory>false</p:isMandatory>
	</p:ProtocolStepToken>
	
</p:Step>

=== eID-Testbeds/server/eidsrv-testbed-testgenerator/src/main/resources/defaultTests/D3/EID_SERVER_D3_06.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:testcaseDefinition xmlns:p="http://www.secunet.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.secunet.com ../../xmlScheme/sn_TestcaseDefinition.xsd ">
	<p:name>EID_SERVER_D3_06</p:name>
	<p:description>Positive test verifying that the eIDAS-Interface of the eID-Server supports the Encrypt-then-MAC extension for TLS.</p:description>
	<p:modulePath>
		<p:node>D</p:node>
		<p:node>3</p:node>
	</p:modulePath>
	<p:profiles>
		<p:profile>EIDAS_MW</p:profile>
		<p:profile>CRYPTO</p:profile>
		<p:profile>TLS_ETM</p:profile>
	</p:profiles>
	<p:eservice>ERSA</p:eservice><p:clientExplanation>Configure the server to accept the certificate chain for client E. This includes the TLS, XML signature and the CV certificate.</p:clientExplanation>
	<p:certificateBaseNames>
		<p:certificate>CERT_EID_TLS_EIDSERVER_1</p:certificate>
	</p:certificateBaseNames>
	<p:steps>
		<p:step>OUT_TLS_ATTACHED</p:step>
	</p:steps>
	<p:variables>
		<p:variable name="TLS_VERSION">TLSv12</p:variable>
		<p:variable name="TLS_SELECTED_VERSION">TLSv12</p:variable>
		<p:variable name="TLS_CIPHER_SUITES">TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA</p:variable>
		<p:variable name="TLS_SELECTED_CIPHER_SUITE">TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA</p:variable>
		<p:variable name="TLS_ALERT_LEVEL_RECEIVED">0</p:variable>
		<p:variable name="TLS_ENCRYPT_THEN_MAC_EXTENSION">true</p:variable>
		<p:variable name="TLS_ENCRYPT_THEN_MAC_EXTENSION_ENABLED">true</p:variable>
	</p:variables>
</p:testcaseDefinition>

=== eID-Testbeds/server/eidsrv-testbed-testgenerator/src/main/resources/steps/IN_USEID_RESPONSE_PSK.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Step xmlns:p="http://www.secunet.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.secunet.com ../xmlScheme/sn_TestcaseDefinition.xsd" >
	<p:TargetInterface>eID-Interface</p:TargetInterface>
	<!-- Schema name -->
	<!--<p:Schema>PROVIDE_XSD</p:Schema> -->
	<!-- HTTP Tokens -->
	<p:HttpStepToken>
		<p:name>HTTP_STATUS_CODE</p:name>
		<p:value>HTTP/1.1 200 OK</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:HttpStepToken>
	<p:HttpStepToken>
		<p:name>Content-Type</p:name>
		<p:value>text/xml;charset=utf-8</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:HttpStepToken>
	<!-- Protocol tokens -->
	<p:ProtocolStepToken>
		<p:name>Session</p:name>
		<p:value></p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ID</p:name>
		<p:parentName>Session</p:parentName>
		<p:value></p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>PSK</p:name>
		<p:value></p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ID</p:name>
		<p:parentName>PSK</p:parentName>
		<p:value>[PSK_ID]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>Key</p:name>
		<p:parentName>PSK</p:parentName>
		<p:value>[PSK_KEY]</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ProtocolStepToken>
		<p:name>ResultMajor</p:name>
		<p:value>http://www.bsi.bund.de/ecard/api/1.1/resultmajor#ok</p:value>
		<p:isMandatory>true</p:isMandatory>
	</p:ProtocolStepToken>
	<p:ToSave parentName="Session" placeholder="ESERVICE_SESSION">ID</p:ToSave>
	<p:ToSave placeholder="PSK">Key</p:ToSave>
	<p:ToSave parentName="PSK" placeholder="SESSIONIDENTIFIER">ID</p:ToSave>
</p:Step>

=== eID-Testbeds/server/eidsrv-testbed-testgenerator/src/main/resources/defaultTests/A1_1/EID_SERVER_A1_1_06.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:testcaseDefinition xmlns:p="http://www.secunet.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.secunet.com ../xmlScheme/sn_TestcaseDefinition.xsd ">
	<p:name>EID_SERVER_A1_1_06</p:name>
	<p:description>Positive test of the eID-Interface interaction in case the terminal CV certificate of the eService contains two terminal sectors.</p:description>
	<p:modulePath>
		<p:node>A</p:node>
		<p:node>1</p:node>
		<p:node>1</p:node>
	</p:modulePath>
	<p:profiles>
		<p:profile>SOAP</p:profile>
		<p:profile>EID_ACCESS</p:profile>
		<p:profile>RI_MIGRATION</p:profile>
	</p:profiles>
	<p:eservice>D</p:eservice><p:clientExplanation>Configure the server to accept the certificate chain for client D. This includes the TLS, XML signature and the CV certificate.</p:clientExplanation>
	<p:eidcard>EIDCARD_1</p:eidcard>
	<p:certificateBaseNames>
		<p:certificate>CERT_EID_TLS_EIDSERVER_1</p:certificate>
	</p:certificateBaseNames>
	<p:steps>
		<p:step>OUT_USEID_REQUEST</p:step>
		<p:step>IN_USEID_RESPONSE</p:step>
		<p:reference targetInterface="eCard-API">EID_SERVER_C1_1_06</p:reference>
		<p:step>OUT_GETRESULT_REQUEST</p:step>
		<p:step>IN_GETRESULT_RESPONSE_RESTRICTEDID</p:step>
	</p:steps>
	<p:variables>
		<p:variable name="USEOP_RESTRICTEDID">REQUIRED</p:variable>
	</p:variables>
</p:testcaseDefinition>

=== eID-Testbeds/server/eidsrv-testbed-testgenerator/src/main/resources/defaultTests/B2_1/EID_SERVER_B2_1_03_DSA.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:testcaseDefinition xmlns:p="http://www.secunet.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.secunet.com ../xmlScheme/sn_TestcaseDefinition.xsd ">
	<p:name>EID_SERVER_B2_1_03_DSA</p:name>
	<p:description>This test case checks the behaviour of the eID-Server in case the SAML message contains an invalid XML signature.</p:description>
	<p:modulePath>
		<p:node>B</p:node>
		<p:node>2</p:node>
		<p:node>1</p:node>
	</p:modulePath>
	<p:profiles>
		<p:profile>SAML</p:profile>
		<p:profile>CRYPTO</p:profile>
	</p:profiles>
	<p:eservice>EDSA</p:eservice><p:clientExplanation>Configure the server to accept the certificate chain for client E. This includes the TLS, XML signature and the CV certificate.</p:clientExplanation>
	<p:certificateBaseNames>
		<p:certificate>CERT_ECARD_TLS_EIDSERVER_1</p:certificate>
	</p:certificateBaseNames>
	<p:steps>
		<p:step>OUT_CALL_SAML_INCL_AUTHNREQUEST</p:step>
		<p:step>IN_BAD_REQUEST</p:step>
	</p:steps>
	<p:variables>
		<p:variable name="XML_SIGNATURE">DSA_MANIPULATED</p:variable>
	</p:variables>
</p:testcaseDefinition>
